name: leave_manager
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_secure_storage: ^8.0.0
  image_picker: ^0.8.6+1
  go_router: ^6.0.9
  flutter_screenutil: ^5.6.1
  flutter_animate: ^4.1.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  getwidget: ^2.0.4
  intl: ^0.18.0
  badges: ^3.1.1
  flutter_native_splash: ^2.2.0
  flutter_launcher_icons: ^0.12.0
  font_awesome_flutter: ^10.4.0
  table_calendar: ^3.0.9
  rflutter_alert: ^2.0.7
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/
